# Generated by Django 2.0.2 on 2018-03-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userBlance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='userIntegral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.IntegerField(unique=True),
        ),
    ]
