# Generated by Django 2.0.2 on 2018-03-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20180316_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
